#!/usr/bin/python3
# EASY-INSTALL-ENTRY-SCRIPT: 'hvac-control','console_scripts','UI'
__requires__ = 'hvac-control'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('hvac-control', 'console_scripts', 'UI')()
    )
